### ISSUE TITLE
Icons are not visible

### ISSUE THREAD

**Issue by RMCoder198** [italia/design-react-kit#105]
**Describe the bug**
In branch `next` icons are not visible
**To Reproduce**
1. Go to Tab component
2. Click on icone
3. See error

**Expected behavior**
Icon should be visible

**Screenshots**
![isone](https://user-images.githubusercontent.com/26675957/54448813-98635000-4772-11e9-8198-da02e65df431.png)

**Other Required Information (please complete the following information):**
 - OS: [ubuntu]
 - Browser [ chrome]

**Comment by francescozaia** [comment]
That's because we moved away from icon fonts, to an svg sprite based way of inserting icons. We need to investigate on how to import svg sprite properly (some [quick](https://www.webdevdrops.com/build-an-svg-icon-component-with-react-de9db211ebd6/) - [random](https://medium.com/@Canfie1d/svg-icon-sets-in-react-with-rollup-cd10be8206a5) [links](https://stackoverflow.com/questions/49736197/using-svg-sprite-with-vue-storybook)).

**Comment by Diuda** [comment]
I tried adding the svg component with `className` as `icon` and `xlinkHref` as `bootstrap-italia/dist/svg/sprite.svg#something` but it still does not show up. Not sure where I am going wrong.

Here's the **screenshot**
![Screenshot from 2019-03-18 15-32-13](https://user-images.githubusercontent.com/12708871/54522435-39c8ec80-4993-11e9-8c29-214b229169b8.png)
