### ISSUE TITLE
[BUG] Toggle can't handle ref and needs key to be rendered correctly

### ISSUE THREAD

**Issue by elgorditosalsero** [italia/design-react-kit#852]
## Describe the bug
The toggle component can't handle the ref passed by libraries like `react-hook-form` as it will throw this warning
![Screenshot 2022-04-20 at 17 31 40](https://user-images.githubusercontent.com/65770455/164267824-79cd7558-fc37-48b9-a583-3c794bb31a0b.png)

As the component can't handle the ref, you won't be able to work with it and handle the state of the component itself via the library.

## To Reproduce
1. Go to [CodeSandbox](https://codesandbox.io/s/warfox-form-406prf?file=/src/App.js)
2. Check `FormWithError` component and try it (take a look at the console and the `handleToggleChange` method.
3. Toggle one of the `required` Toggle and hit submit.
4. As you can see, the value of the `visible` input is updated correctly but the component is not rendered correctly.

## Expected behavior
`<Toggle>` should handle the ref correctly.

I would suggest removing the [`FC` type](https://github.com/italia/design-react-kit/blob/master/src/Toggle/Toggle.tsx) as is useless and you're passing `children` prop to the input... and this is not an expected behaviour , and if needed, applying `forwardRef`

## Screenshots
![Screenshot 2022-04-20 at 17 31 40](https://user-images.githubusercontent.com/65770455/164267824-79cd7558-fc37-48b9-a583-3c794bb31a0b.png)

**Additional context**
I temporarily fixed the issue, removing the ref (as the component is expecting `innerRef`, instead of `ref`), adding `key` to each `<Toggle> ` in order to re-render it based on the value inside the form.

You can check this behavior inside the `Form` component

**Comment by dej611** [comment]
> <Toggle> should handle the ref correctly.

It does already, but via the `innerRef` prop rather than the `ref` one.
This library is built on top of `reactstrap` which uses this pattern: forwarding the `ref` here means to monkey-patch all `reactstrap` component as well, or juggle with them if used under the hood, which is not in scope for the kit.

> I would suggest removing the [FC type](https://github.com/italia/design-react-kit/blob/master/src/Toggle/Toggle.tsx) as is useless and you're passing children prop to the input...

Also this point is inherited from `reactstrap` which provides a runtime validation for it. Not great, but that's the library behaviour.

> I temporarily fixed the issue, removing the ref (as the component is expecting innerRef, instead of ref),

This is the actual solution, as recommended by the `react-hook-form` mantainers as well, to work with `reactstrap` and related libraries.
If you want to spread the `fieldProps` on the component but remove the `ref` prop to avoid this error you could destructure as follow:

```
<Controller
                      name='checkbox'
                      control={control}
                      rules={{ required: true }}
                      render={({ field: { ref, ...fieldProps } }) => (
                        <Toggle
                          {...fieldProps}
                          defaultChecked={fieldProps.value}
                          innerRef={ref}
                          onClick={() => console.log('Toggle')}
                          value={`input_visible`}
                          label={'input_visible'}
                        />
                      )}
                    />
```
